### PR TITLE
doc: Add install instructions to repo

### PR DESCRIPTION
**Pull request by emich-kyle**

### CODE REVIEW

**Comment by emich-kyle** [comment]
thanks @rrstem for the helpful install instructions

**Comment by mzindah** [comment]
Read through the entire document and it looks really good! Super easy to read/follow. I believe there are no errors/issues in the instructions. Nice job!

**Comment by rrstem** [comment]
Thanks for getting the branch & PR set up, Kyle!

**Comment by XillaBird** [comment]
Looks great, loved the user input being put in blue and separated by " ` ".

**Comment by sheaail** [comment]
Install instructions look great! They're super clear and detailed!

**Comment by phoenixffire** [comment]
Thumbs up from me. Instructions are clear and installation is straightforward.

**Comment by Ebooher** [comment]
Straight forward and clear!

**Pull request merged**
