### PR TITLE
doc: Added File Standards for Go and React to Readme.

### PR DESCRIPTION
**Pull request by phoenixffire**
React Standards - Focuses on features provided. Each feature will have it's own folder, with a common folder for any shared code. Inspiration was found at https://reactjs.org/docs/faq-structure.html. This method keeps code that interacts with each other with the code it interacts with, with a separate common folder for any code that is shared between features.

Go Standards - Focuses on use and position of the code within the workflow. The folders will denote what kind of code can be found within. This method was found at https://github.com/golang-standards/project-layout. This method keeps the directories focused on their single issues and helps to mitigate bloat from any test code.

### CODE REVIEW

**Comment by mzindah** [comment]
Thank you Alex! I looked it over and the standards look good and are easy to follow. I appreciate that you added separate sections for Go standards and React standards.

**Comment by rrstem** [comment]
Looks good, Alex. Thanks for doing the Research. I will open up a new issue to properly set up the current file structure to reflect these standards.

**Comment by rrstem** [comment]
In regards to the Go file structure: The api/ directory will contain information & documentation for using and making calls to the back end's REST API. This will be a useful directory for the front end team, as it will be any easy and quick way to see how they can interact with the back end.

**Comment by XillaBird** [comment]
Good job Alex, examples are clear to follow.

**Comment by sheaail** [comment]
Great research Alex. The examples are very helpful!

**Comment by emich-kyle** [comment]
thanks @phoenixffire detailing the file standards for each language is very helpful

**Comment by emich-kyle** [comment]
the /cmd folder contains the main application entry point files for the Go project, with the directory name matching the name for the binary. For example cmd/flashfolio means that the binary we publish will be flashfolio; cmd/login means the binary we publish will be login

**Comment by Ebooher** [comment]
The front end directory will hold the react code and html, css files to display to the user. While backend will have our GO code and database the the user won't directly interact with.

**Pull request merged**
